

create view [CATEGORIAS COM ORDERS] as
select 
	o.ORDER_ID
	,o.ORDER_PURCHASE_TIMESTAMP
	,o.CUSTOMER_ID
	,o.ORDER_APPROVED_AT
	,o.ORDER_DELIVERED_CARRIER_DATE
	,o.ORDER_DELIVERED_CUSTOMER_DATE
	,o.ORDER_ESTIMATED_DELIVERY_DATE
	,o.ORDER_STATUS
	,p.PRODUCT_ID
	,p.PRODUCT_CATEGORY_NAME
from TB_ACT_ORDERS o 
	 join TB_ACT_PRODUCTS p on o.PRODUCT_ID = p.PRODUCT_ID